version: "3.8"

services:
  app:
    image: localhost/manga:latest
    expose:
      - 8787
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CHARSET=${DB_CHARSET}
      - DB_COLLATION=${DB_COLLATION}
      - DB_PREFIX=${DB_PREFIX}

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80 

  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - nginx
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
