name: Nzha Agent

on:
  schedule:
    - cron: "0 */6 * * *"   # chạy mỗi 6 tiếng
  workflow_dispatch:   # chạy thủ công từ giao diện GitHub
 # push:                # hoặc bạn có thể bật khi push code
  #  branches:
   #   - main

jobs:
  run-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cài Nezha Agent
        run: |
          curl -L https://raw.githubusercontent.com/nezhahq/scripts/main/install_en.sh -o nezha.sh
          chmod +x nezha.sh
          ./nezha.sh install_agent ${{ secrets.NEZHA_DOMAIN }} 443 ${{ secrets.NEZHA_KEY }} --tls

      - name: Giữ job chạy
        run: |
          while true; do
            echo "[$(date)] Nezha Agent is active - Use Ctrl+C in workflow to terminate"
            sleep 300
          done
