name: Nzha Agent

on:
  schedule:
    - cron: '0 0 * * *'   # 00:00 UTC
    - cron: '50 5 * * *'  # 05:50 UTC
    - cron: '40 11 * * *' # 11:40 UTC
    - cron: '30 17 * * *' # 17:30 UTC
    - cron: '20 23 * * *' # 23:20 UTC
  workflow_dispatch:   # chạy thủ công từ giao diện GitHub
 # push:                # hoặc bạn có thể bật khi push code
  #  branches:
   #   - main

jobs:
  run-agent:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cài Nezha Agent
        run: |
          curl -L https://raw.githubusercontent.com/nezhahq/scripts/main/install_en.sh -o nezha.sh
          chmod +x nezha.sh
          ./nezha.sh install_agent ${{ secrets.NEZHA_DOMAIN }} 443 ${{ secrets.NEZHA_KEY }} --tls

      - name: Giữ job chạy
        run: |
          while true; do
            echo "[$(date)] Use Ctrl+C in workflow to terminate"
            sleep 300
          done
